# Generated by Django 5.2.15 on 2026-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
    ]
