# Generated by Django 5.2.15 on 2026-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testsession_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='generating', max_length=20),
        ),
    ]
