# Generated by Django 5.2.15 on 2026-09-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertest',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
    ]
